#consu: consulFromServerConfig-test

#kafka
#spring.cloud.stream.kafka.binder.zk-nodes: 172.16.0.27:2181
#spring.cloud.stream.kafka.binder.brokers: 172.16.0.27:9092
#spring.cloud.bus.trace.enabled: true