spring:
  application:
    name: eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.registry.peer1.url},${eureka.registry.peer2.url}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

spring.cloud.circuit.breaker.enabled: true
ribbon.custom.app.name: eureka-provider
consumerkey: ${eureka.registry.peer1.url}