eureka.server.ip.peer1: 127.0.0.1
eureka.server.ip.peer2: 127.0.0.1
eureka.server.ip.peer3: 127.0.0.1
eureka.server.ip.peer4: 127.0.0.1
peer1.port: 8761
peer2.port: 8762
peer3.port: 8763
peer4.port: 8764

server.url.peer1: http://horcrux:hor66@${eureka.server.ip.peer1}:${peer1.port}/eureka/
server.url.peer2: http://horcrux:hor66@${eureka.server.ip.peer3}:${peer2.port}/eureka/
server.url.peer3: http://horcrux:hor66@${eureka.server.ip.peer3}:${peer3.port}/eureka/

client.serverURL: ${server.url.peer1},${server.url.peer2},${server.url.peer3}