eureka.server.ip: 172.20.0.15
spring:
  application:
    name: zuul-file-upload
eureka:
  client:
    serviceUrl:
      defaultZone:  http://horcrux:horcrux66@${eureka.server.ip}:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}