server:
  port: 8200
spring:
  application:
    name: eureka-provider-peer1
eureka:
  client:
    serviceUrl:
      defaultZone: ${server.peer1}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

