spring:
  application:
    name: eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://horcrux:horcrux66@172.20.0.15:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

spring.cloud.circuit.breaker.enabled: true
ribbon.custom.app.name: eureka-provider
consumerkey: consumerFromConfig